image:
  name: amazoncorretto:17
  pull_policy: if-not-present

stages:
  - build
  - test

build:
  stage: build
  script:
    - chmod +x ./mvnw
    - ./mvnw clean install -DskipTest

test:
  stage: test
  script:
    - chmod +x ./mvnw
    - ./mvnw test
